query FindAllPost($name: String!) {
  findAllPost(name: $name) {
    content
    createdAt
    id
    postCount {
      forward
      isForward
      isLike
      isReply
      isStar
      like
      reply
    }
    profileCount {
      followed
      followings
      posts
    }
    user {
      image
      name
      nickName
      bio
    }
  }
}
