query GetHomePost($name: String!, $pageIndex: Float!) {
  getHomePost(name: $name, pageIndex: $pageIndex) {
    content
    createdAt
    id
    postCount {
      forward
      isForward
      isLike
      isReply
      isStar
      like
      reply
    }
    profileCount {
      followed
      followings
      posts
    }
    user {
      bio
      image
      name
      nickName
    }
  }
}
