query GetPostById($name: String!, $id: Float!) {
  getPostById(name: $name, id: $id) {
    id
    content
    createdAt
    postCount {
      forward
      isForward
      isLike
      isReply
      isStar
      like
      reply
    }
    profileCount {
      followed
      followings
      posts
    }
    user {
      bio
      image
      name
      nickName
    }
  }
}
