import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { notFound } from 'next/navigation'
import type { ReactNode } from 'react'
import Sidebar from '@/components/sidebar/SideBar'
import AuthProvider from '@/context/AuthProvider'
import ApolloProvider from '@/context/ApolloProvider'
import Alert from '@/components/ui/Alert'

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'zh' }]
}

interface Props {
  children: ReactNode
  params: { locale: string }
}

export const metadata: Metadata = {
  title: 'StarTree',
  description: 'Generated by create next app',
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: Props) {
  let messages
  try {
    messages = (await import(`../../messages/${locale}.json`)).default
  }
  catch (error) {
    notFound()
  }

  return (
    <html lang={locale} className='dark'>
      <body>
        <AuthProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <ApolloProvider >
              <div
                className="flex justify-center w-screen h-screen overflow-x-hidden overflow-y-auto xl:gap-4 bg-base text-bs "
                style={{
                  fontSize: 'var(--font-size)',
                }}
              >
                <Sidebar />
                <div className="xl:min-w-[900px] flex">
                  {children}
                </div>
              </div>
              <Alert />
            </ApolloProvider>
          </NextIntlClientProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
