query GetLikePost($userName: String!) {
  getLikePost(userName: $userName) {
    content
    createdAt
    id
    postCount {
      forward
      isForward
      isLike
      isReply
      isStar
      like
      reply
    }
    profileCount {
      followed
      followings
      posts
    }
    user {
      image
      name
      nickName
    }
  }
}

