mutation CreateUser($createUserInput: CreateUserInput!) {
  createUser(createUserInput: $createUserInput) {
    name
    image
    email
    nickName
    profile {
      id
      github
      bio
      website
    }
  }
}
