query Profile($name: String!) {  
  userData(name: $name) {
    name
    nickName
    image
    email
    createdAt
    profile {
      bio
      github
      website
    }
  }
  profileCount(name: $name) {
    followed
    followings
    posts
  }
  getProfileData(name: $name) {
    followed {
      name
      nickName
      image
    }
    followings {
      name
      nickName
      image
    }
    posts {
      content
      createdAt
      id
      postCount {
        forward
        isForward
        isLike
        isReply
        isStar
        like
        reply
      }
      profileCount {
        followed
        followings
        posts
      }
      user {
        image
        name
        nickName
      }
    }
  }

}
