mutation UpdateUserProfile($updateUserInput: UpdateUserInput!) {
  updateUserProfile(updateUserInput: $updateUserInput) {
    profile {
      bio
      github
      id
      website
    }
    name
    email
    image
    nickName
  }
}
